sonar.projectKey=student-api
sonar.projectName=student-api

sonar.sources=.
sonar.tests=tests

sonar.inclusions=app.py
sonar.test.inclusions=tests/**/*.py

sonar.exclusions=venv/**,__pycache__/**,.pytest_cache/**

sonar.python.version=3.13